# Generated by Django 4.2.17 on 2025-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_images/'),
        ),
    ]
